/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulários;

/**
 *
 * @author CAMARGO
 */
public class Calculo extends javax.swing.JFrame {

    /**
     * Creates new form Calculo
     */
    public Calculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        variavel1 = new javax.swing.JPanel();
        txt_n1 = new javax.swing.JLabel();
        txt_n2 = new javax.swing.JLabel();
        txt_n3 = new javax.swing.JLabel();
        botaoSoma = new javax.swing.JButton();
        botaoMenos = new javax.swing.JButton();
        botaoMultiplicacao = new javax.swing.JButton();
        botaoDivisao = new javax.swing.JButton();
        botaoRetornar = new javax.swing.JButton();
        botaoComparacao = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        variavel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programação de Computadores", null, null, new java.awt.Font("Tw Cen MT", 0, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        variavel1.setToolTipText("");
        variavel1.setAutoscrolls(true);
        variavel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_n1.setText("N1");

        txt_n2.setText("N2");

        txt_n3.setText("Resultado");

        botaoSoma.setText("+");
        botaoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSomaActionPerformed(evt);
            }
        });

        botaoMenos.setText("-");
        botaoMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenosActionPerformed(evt);
            }
        });

        botaoMultiplicacao.setText("*");
        botaoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMultiplicacaoActionPerformed(evt);
            }
        });

        botaoDivisao.setText("/");
        botaoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDivisaoActionPerformed(evt);
            }
        });

        botaoRetornar.setText("Retornar");

        botaoComparacao.setText("Comparação");

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoNovo.setText("Novo");

        javax.swing.GroupLayout variavel1Layout = new javax.swing.GroupLayout(variavel1);
        variavel1.setLayout(variavel1Layout);
        variavel1Layout.setHorizontalGroup(
            variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variavel1Layout.createSequentialGroup()
                .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(variavel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_n2)
                            .addComponent(txt_n1))
                        .addGap(43, 43, 43)
                        .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(variavel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_n3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(variavel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(botaoSoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoMenos)
                .addGap(12, 12, 12)
                .addComponent(botaoMultiplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoDivisao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoRetornar)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, variavel1Layout.createSequentialGroup()
                .addComponent(botaoNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(botaoLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSair)
                .addGap(53, 53, 53)
                .addComponent(botaoComparacao)
                .addGap(19, 19, 19))
        );
        variavel1Layout.setVerticalGroup(
            variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variavel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_n1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_n2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_n3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSoma)
                    .addComponent(botaoMenos)
                    .addComponent(botaoMultiplicacao)
                    .addComponent(botaoDivisao)
                    .addComponent(botaoRetornar))
                .addGap(27, 27, 27)
                .addGroup(variavel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoComparacao)
                    .addComponent(botaoSair)
                    .addComponent(botaoLimpar)
                    .addComponent(botaoNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(variavel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(variavel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSomaActionPerformed
        int x, y, z; //declarando os números que serão inseridos
        String r; // String para receber os valores
        
        x = Integer.parseInt( txt_n1.getText()); 
        y = Integer.parseInt( txt_n2.getText());
        
        z = x + y; //Operação
        
        r = String.valueOf(z); //Passando a variável para String
        txt_n3.setText(r); //Campo de resposta recebendo o valor
    }//GEN-LAST:event_botaoSomaActionPerformed

    private void botaoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMultiplicacaoActionPerformed
        int x, y, z; //declarando os números que serão inseridos
        String r; // String para receber os valores
        
        x = Integer.parseInt( txt_n1.getText()); 
        y = Integer.parseInt( txt_n2.getText());
        
        z = x * y; //Operação
        
        r = String.valueOf(z); //Passando a variável para String
        txt_n3.setText(r); //Campo de resposta recebendo o valor
    }//GEN-LAST:event_botaoMultiplicacaoActionPerformed

    private void botaoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDivisaoActionPerformed
        int x, y, z; //declarando os números que serão inseridos
        String r; // String para receber os valores
        
        x = Integer.parseInt( txt_n1.getText()); 
        y = Integer.parseInt( txt_n2.getText());
        
        z = x / y; //Operação
        
        r = String.valueOf(z); //Passando a variável para String
        txt_n3.setText(r); //Campo de resposta recebendo o valor
    }//GEN-LAST:event_botaoDivisaoActionPerformed

    private void botaoMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenosActionPerformed
        int x, y, z; //declarando os números que serão inseridos
        String r; // String para receber os valores
        
        x = Integer.parseInt( txt_n1.getText()); 
        y = Integer.parseInt( txt_n2.getText());
        
        z = x - y; //Operação
        
        r = String.valueOf(z); //Passando a variável para String
        txt_n3.setText(r); //Campo de resposta recebendo o valor
    }//GEN-LAST:event_botaoMenosActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        txt_n1.setText("");
        txt_n2.setText("");
        txt_n3.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoComparacao;
    private javax.swing.JButton botaoDivisao;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoMenos;
    private javax.swing.JButton botaoMultiplicacao;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoRetornar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSoma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel txt_n1;
    private javax.swing.JLabel txt_n2;
    private javax.swing.JLabel txt_n3;
    private javax.swing.JPanel variavel1;
    // End of variables declaration//GEN-END:variables
}
